### PR TITLE
Removes tray app

### PR DESCRIPTION
**Pull request by carsonfarmer**
In favor of the new one over at https://github.com/textileio/desktop. This also `tidy`s out the go modules that were specific to the tray app.

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Let's hold off on merging this until the issues with CI are sorted over in github.com/textileio/desktop though.

**Comment by sanderpick** [comment]
Probably in there and I just cant see it, but does this update the CI config?

**Comment by carsonfarmer** [comment]
@sanderpick ci stuff updated. We could also probably update the Docker image because we don't need yarn etc anymore?

**Comment by carsonfarmer** [comment]
Should be GTG now @sanderpick

**Pull request merged**
