### PR TITLE
[wip] Tiny nits and things that might actually be irrelevant but I don't want to lose them...

### PR DESCRIPTION
**Pull request by carsonfarmer**
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

### CODE REVIEW

**Comment by balupton** [comment]
@sanderpick can I get write permissions on circleci so I can rerun these unit tests

Screen Shot 2019-06-26 at 1 23 50 am

**Comment by sanderpick** [comment]
You should already have permission - it's inherited from GH. You just need to "follow" the project in CIrcleCI.

**Comment by sanderpick** [comment]
If you go here: https://circleci.com/gh/textileio/go-textile and click the little gear in the upper right, you should be able to follow the project. You can follow all the textile ones.

**Comment by sanderpick** [comment]
still needed @carsonfarmer?

**Pull request merged**
