### PR TITLE
globals_flags: fix proposal #879

### PR DESCRIPTION
**Pull request by ilpaijin**
### 879 fix proposal
It seems it needs to be a hook PreAction which disables the unwanted flags declared in the main Application cmd.
Before parsing, choose an arbitrary list of cmds (it could have been a single call per cmd, or others...I didn't get you way of design it so I simply choose one way)

### CODE REVIEW

**Comment by sanderpick** [comment]
Hey @ilpaijin - This looks like a reasonable approach, thanks! Can you add a sign-off to your commit? 

```
git commit --amend --signoff
git push --force-with-lease origin issue/879
```

**Comment by ilpaijin** [comment]
sure @sanderpick, done. If you don't mind I'll try to check for other issues, some easy to pick for me.

**Comment by sanderpick** [comment]
Oh, it would be nice to allow `--help` to still come through for `init`, `daemon`, and `wallet`. Maybe you can filter that out of the hide step.

As for working on other issues, of course... any help is much appreciated.

**Comment by ilpaijin** [comment]
ok nice tx

**Pull request merged**
