### PR TITLE
API middleware move

### PR DESCRIPTION
**Pull request by carsonfarmer**

### CODE REVIEW

**Comment by sanderpick** [comment]
I fixed the build issue - it’s in master now

**Comment by carsonfarmer** [comment]
nice, didn't see that quick fix!

**Comment by carsonfarmer** [comment]
This middleware fix is useful on its own none the less tho @carsonfarmer.

**Comment by carsonfarmer** [comment]
Context: The middleware wasn't applying to the endpoints specified before the middleware was specified.

**Pull request merged**
